config/routes.rb
Gorrion::Application.routes.draw do

  namespace :sigesp do
    resources :solicituds
    resources :solicitudsalmacens
  end

  devise_for :usuarios, class_name: "Administracion::Usuario"
  namespace :administracion do
    resources :usuarios do        
        get 'permisos', to: 'usuarios#permisos_usuario'
        post 'permiso/:permiso_id/add/', to: 'usuarios#add_permiso_usuario' , as: :permiso_add
        post 'permiso/:permiso_id/del/', to: 'usuarios#del_permiso_usuario', as: :permiso_del 
        get   'password' , to: 'usuarios#password_edit'
        patch 'password' , to: 'usuarios#password_save'      
      end 
  end

  namespace :sigesp do
    get 'tiposArticulos/',to: 'tipoarticulo#tiposArticulos'
    get 'articulos/', to: 'articulos#index' , as: :articulos
    get 'servicios/', to: 'sede_servicio#index', as: :servicios
    get 'unidadAdministrativas/', to: 'unidad_administrativa#index', as: :unidad_administrativas
  end

  namespace :admin do
     resources :usuarios
  end

  root 'welcome#index'

end

app/models/sigesp.rb
module Sigesp
  def self.table_name_prefix
    'sigesp_'
  end
end

app/models/sigesp/almacen.rb
class Sigesp::Almacen < ActiveRecord::Base
	self.primary_key = 'codalm'
	self.table_name = 'public.siv_almacen'

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/articulo.rb
class Sigesp::Articulo < ActiveRecord::Base
	self.primary_key = 'codart'
	self.table_name = 'public.siv_articulo'

	belongs_to :unidad, foreign_key: "codunimed", class_name: "Sigesp::Unidad"
	belongs_to :tipo_articulo, foreign_key: "codtipart", class_name: "Sigesp::TipoArticulo"

	# has_and_belongs_to_many :cargos, class_name: "Sigesp::Cargo", join_table: "public.siv_cargosarticulo", foreign_key:"codart" ,association_foreign_key: "codcar"    
    belongs_to :dt_cargo, foreign_key: "codemp", class_name: "Sigesp::DtCargo"

    has_many :cargos_articulos, class_name: "Sigesp::DtCargo", foreign_key:"codart"
	has_many :cargos, class_name: "Sigesp::Cargo", through: :cargos_articulos 


	
	self.per_page = 10 

	def cargo_activo
		if cargos.size == 0 
			return 0
		end 

		if  cargos[0].nil? 
			cargo = 0
		else
			cargo = cargos[0].porcar 
		end 
	end 

	def self.search(page = 1 , search , sort)
	    search ||= ""
   	 	sort = "codart" if sort =="codigo"
   	 	sort = "denart" if sort == "descripcion"
    
	    if search.empty? 
	      paginate(page: page).includes(:cargos).references(:cargos).order(sort) rescue paginate(page: 1).includes(:cargos).references(:cargos)
	    else
	      paginate(page: page).where("#{sort} like ?","%#{search}%").includes(:cargos).references(:cargos).order("#{sort} asc")
	    end 
	end 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/cargo.rb
class Sigesp::Cargo < ActiveRecord::Base
	self.primary_key = 'codcar'
	self.table_name = 'public.sigesp_cargos'

	belongs_to :dt_cargo, foreign_key: "codemp", class_name: "Sigesp::DtCargo"

	belongs_to :solicitud_cargo, foreign_key: "codemp", class_name: "Sigesp::SolicitudCargo"

	has_many :articulos_cargos, class_name: "Sigesp::DtCargo", foreign_key:"codcar"
	has_many :articulos, class_name: "Sigesp::Articulo", through: :articulos_cargos 


	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/ctrl_requisicion.rb
class Sigesp::CtrlRequisicion < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'sigesp_espc.sigesp_ctrl_requisicion'

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/cuenta_gasto.rb
class Sigesp::CuentaGasto < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_cuentagasto'

	belongs_to :solicitud, foreign_key: "numsol", class_name: "Sigesp::Solicitud"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/departamento.rb
class Sigesp::Departamento < ActiveRecord::Base
	self.primary_key = 'coddep'
	self.table_name = 'sigesp_espc.sno_departamento'

	belongs_to :responsable, foreign_key: "codperresponsable",class_name: "Sigesp::Persona" 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/dt_articulo.rb
class Sigesp::DtArticulo < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_dt_articulos'

	belongs_to :solicitud, foreign_key: "numsol", class_name: "Sigesp::Solicitud"
	belongs_to :articulo, foreign_key: "codart", class_name: "Sigesp::Articulo"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/dt_cargo.rb
class Sigesp::DtCargo < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_dta_cargos'

	belongs_to :cargo, class_name: "Sigesp::Cargo", foreign_key:"codcar"
    belongs_to :articulo, class_name: "Sigesp::Articulo", foreign_key:"codart"


	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/dts_cargo.rb
class Sigesp::DtsCargo < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_dts_cargos'

	belongs_to :cargo, foreign_key: "codcar", class_name: "Sigesp::Cargo"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/fuente_financiamiento.rb
class Sigesp::FuenteFinanciamiento < ActiveRecord::Base
	self.primary_key = 'codfuefin'
	self.table_name = 'public.sigesp_fuentefinanciamiento'

	 belongs_to :spg_ep3, foreign_key: "codemp", class_name: "Sigesp::SpgEp3"
	 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/marca.rb
class Sigesp::Marca < ActiveRecord::Base
	self.primary_key = 'str_idmarca'
	self.table_name = 'sigesp_espc.siv_marca'

	has_many :modelos, class_name: "Sigesp::Modelo", foreign_key:"str_idmarca"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end  
end

app/models/sigesp/modelo.rb
class Sigesp::Modelo < ActiveRecord::Base
	self.primary_key = 'id_modelo'
	self.table_name = 'sigesp_espc.siv_modelo'

	belongs_to :marca, foreign_key: "str_idmarca", class_name: "Sigesp::Marca" 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/persona.rb
class Sigesp::Persona < ActiveRecord::Base
	self.primary_key = 'codper'
	self.table_name = 'public.sno_personal'
	
	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/region.rb
class Sigesp::Region < ActiveRecord::Base
	self.primary_key = 'seq_region'
	self.table_name = 'sigesp_espc.sigesp_regiones'
	
	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/sede.rb
class Sigesp::Sede < ActiveRecord::Base
	self.primary_key = 'seq_sede'
	self.table_name = 'sigesp_espc.sigesp_sedes'

	belongs_to :region, foreign_key: "int_region",class_name: "Sigesp::Region" 
	has_and_belongs_to_many :servicios, class_name: "Sigesp::Servicio",join_table: "sigesp_espc.sigesp_serviciosedes",foreign_key:"int_sede" ,association_foreign_key: "int_servicio"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/servicio.rb
class Sigesp::Servicio < ActiveRecord::Base

	self.primary_key = 'seq_servicio'
	self.table_name = 'sigesp_espc.sigesp_servicios'

	belongs_to :tipo_servicio, foreign_key: "codtipser", class_name: "Sigesp::TipoServicio"  

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/solicitud.rb
class Sigesp::Solicitud < ActiveRecord::Base
	self.primary_key = 'numsol'
	self.table_name = 'public.sep_solicitud'

	  has_many :cuentaGastos, class_name: "Sigesp::CuentaGasto", foreign_key:"numsol"
    has_many :solicitudUsers, class_name: "Sigesp::SolicitudUser", foreign_key:"numsol"
    has_many :solicitudTipos, class_name: "Sigesp::SolicitudTipo", foreign_key:"numsol"
    has_many :dtArticulos, class_name: "Sigesp::DtArticulo", foreign_key: "numsol"
    
    belongs_to :solicitud_cargo, foreign_key: "codemp", class_name: "Sigesp::SolicitudCargo"
    belongs_to :unidadAdministrativa, foreign_key: "coduniadm", class_name: "Sigesp::UnidadAdministrativa"
    belongs_to :tipoSolicitud, foreign_key: "codtipsol", class_name: "Sigesp::TipoSolicitud"

    belongs_to :sede , foreign_key: "cod_sede", class_name: "Sigesp::Sede"
    belongs_to :servicio, foreign_key:"cod_servicio", class_name: "Sigesp::Servicio"

    belongs_to :fuenteFinanciamiento,foreign_key:"codfuefin", class_name: "Sigesp::FuenteFinanciamiento"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end


  def self.search_compra(page = 1 , search , sort)
    search ||= ""
    sort ||= "" 
    join =" INNER JOIN sigesp_espc.sep_solicitud_tipo ON sigesp_espc.sep_solicitud_tipo.numsol = public.sep_solicitud.numsol" 
    if search.empty? 
      joins(join).paginate(page: page).where("sigesp_espc.sep_solicitud_tipo.bol_compra = true ").order(sort) #rescue paginate(page: 1) 
    else
      paginate(page: page).where("#{sort} like ?","%#{search}%").order("#{sort} asc")
    end 
  end 

  def self.search_almacen(page = 1 , search , sort)
    search ||= ""
    sort ||= "" 
    join =" INNER JOIN sigesp_espc.sep_solicitud_tipo ON sigesp_espc.sep_solicitud_tipo.numsol = public.sep_solicitud.numsol" 
    if search.empty? 
      joins(join).paginate(page: page).where("sigesp_espc.sep_solicitud_tipo.bol_compra = false ").order(sort) #rescue paginate(page: 1) 
    else
      paginate(page: page).where("#{sort} like ?","%#{search}%").order("#{sort} asc")
    end 
  end 



   self.per_page = 10 

end

app/models/sigesp/solicitud_cargo.rb
class Sigesp::SolicitudCargo < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_solicitudcargos'

	has_many :cargos, class_name: "Sigesp::Cargo", foreign_key:"codemp"
    has_many :solicituds, class_name: "Sigesp::Solicitud", foreign_key:"codemp"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/solicitud_tipo.rb
class Sigesp::SolicitudTipo < ActiveRecord::Base
	self.primary_key = 'numsol'
	self.table_name = 'sigesp_espc.sep_solicitud_tipo'

	belongs_to :solicitud, foreign_key: "numsol", class_name: "Sigesp::Solicitud" 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/views/sigesp/solicitudsalmacens/_form.html.erb
<%= form_for(@sigesp_solicitud) do |f| %>
  <% if @sigesp_solicitud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sigesp_solicitud.errors.count, "error") %> prohibited this sigesp_solicitud from being saved:</h2>

      <ul>
      <% @sigesp_solicitud.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codemp %><br>
    <%= f.text_field :codemp %>
  </div>
  <div class="field">
    <%= f.label :numsol %><br>
    <%= f.text_field :numsol %>
  </div>
  <div class="field">
    <%= f.label :codtipsol %><br>
    <%= f.text_field :codtipsol %>
  </div>
  <div class="field">
    <%= f.label :coduniadm %><br>
    <%= f.text_field :coduniadm %>
  </div>
  <div class="field">
    <%= f.label :codfuefin %><br>
    <%= f.text_field :codfuefin %>
  </div>
  <div class="field">
    <%= f.label :fecregsol %><br>
    <%= f.date_select :fecregsol %>
  </div>
  <div class="field">
    <%= f.label :estsol %><br>
    <%= f.text_field :estsol %>
  </div>
  <div class="field">
    <%= f.label :consol %><br>
    <%= f.text_field :consol %>
  </div>
  <div class="field">
    <%= f.label :monto %><br>
    <%= f.text_field :monto %>
  </div>
  <div class="field">
    <%= f.label :monbasinm %><br>
    <%= f.text_field :monbasinm %>
  </div>
  <div class="field">
    <%= f.label :montotcar %><br>
    <%= f.text_field :montotcar %>
  </div>
  <div class="field">
    <%= f.label :tipo_destino %><br>
    <%= f.text_field :tipo_destino %>
  </div>
  <div class="field">
    <%= f.label :cod_pro %><br>
    <%= f.text_field :cod_pro %>
  </div>
  <div class="field">
    <%= f.label :ced_bene %><br>
    <%= f.text_field :ced_bene %>
  </div>
  <div class="field">
    <%= f.label :firnivsol %><br>
    <%= f.text_field :firnivsol %>
  </div>
  <div class="field">
    <%= f.label :firnivadm %><br>
    <%= f.text_field :firnivadm %>
  </div>
  <div class="field">
    <%= f.label :firnivpre %><br>
    <%= f.text_field :firnivpre %>
  </div>
  <div class="field">
    <%= f.label :estapro %><br>
    <%= f.number_field :estapro %>
  </div>
  <div class="field">
    <%= f.label :fecaprsep %><br>
    <%= f.date_select :fecaprsep %>
  </div>
  <div class="field">
    <%= f.label :codaprusu %><br>
    <%= f.text_field :codaprusu %>
  </div>
  <div class="field">
    <%= f.label :numpolcon %><br>
    <%= f.text_field :numpolcon %>
  </div>
  <div class="field">
    <%= f.label :fechaconta %><br>
    <%= f.date_select :fechaconta %>
  </div>
  <div class="field">
    <%= f.label :fechaanula %><br>
    <%= f.date_select :fechaanula %>
  </div>
  <div class="field">
    <%= f.label :monbasinmaux %><br>
    <%= f.text_field :monbasinmaux %>
  </div>
  <div class="field">
    <%= f.label :montotcaraux %><br>
    <%= f.text_field :montotcaraux %>
  </div>
  <div class="field">
    <%= f.label :montoaux %><br>
    <%= f.text_field :montoaux %>
  </div>
  <div class="field">
    <%= f.label :undadm %><br>
    <%= f.text_field :undadm %>
  </div>
  <div class="field">
    <%= f.label :destino %><br>
    <%= f.text_field :destino %>
  </div>
  <div class="field">
    <%= f.label :cod_servicio %><br>
    <%= f.text_field :cod_servicio %>
  </div>
  <div class="field">
    <%= f.label :cod_sede %><br>
    <%= f.text_field :cod_sede %>
  </div>
  <div class="field">
    <%= f.label :cod_region %><br>
    <%= f.text_field :cod_region %>
  </div>
  <div class="field">
    <%= f.label :str_codregionsedeservicio %><br>
    <%= f.text_field :str_codregionsedeservicio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sigesp/solicitudsalmacens/edit.html.erb
<h1>Editing sigesp_solicitud</h1>

<%= render 'form' %>

<%= link_to 'Show', @sigesp_solicitud %> |
<%= link_to 'Back', sigesp_solicituds_path %>

app/views/sigesp/solicitudsalmacens/index.html.erb
<h1>Listing sigesp_solicituds</h1>

<table>
  <thead>
    <tr>
      <th>Codemp</th>
      <th>Numsol</th>
      <th>Codtipsol</th>
      <th>Coduniadm</th>
      <th>Codfuefin</th>
      <th>Fecregsol</th>
      <th>Estsol</th>
      <th>Consol</th>
      <th>Monto</th>
      <th>Monbasinm</th>
      <th>Montotcar</th>
      <th>Tipo destino</th>
      <th>Cod pro</th>
      <th>Ced bene</th>
      <th>Firnivsol</th>
      <th>Firnivadm</th>
      <th>Firnivpre</th>
      <th>Estapro</th>
      <th>Fecaprsep</th>
      <th>Codaprusu</th>
      <th>Numpolcon</th>
      <th>Fechaconta</th>
      <th>Fechaanula</th>
      <th>Monbasinmaux</th>
      <th>Montotcaraux</th>
      <th>Montoaux</th>
      <th>Undadm</th>
      <th>Destino</th>
      <th>Cod servicio</th>
      <th>Cod sede</th>
      <th>Cod region</th>
      <th>Str codregionsedeservicio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sigesp_solicituds.each do |sigesp_solicitud| %>
      <tr>
        <td><%= sigesp_solicitud.codemp %></td>
        <td><%= sigesp_solicitud.numsol %></td>
        <td><%= sigesp_solicitud.codtipsol %></td>
        <td><%= sigesp_solicitud.coduniadm %></td>
        <td><%= sigesp_solicitud.codfuefin %></td>
        <td><%= sigesp_solicitud.fecregsol %></td>
        <td><%= sigesp_solicitud.estsol %></td>
        <td><%= sigesp_solicitud.consol %></td>
        <td><%= sigesp_solicitud.monto %></td>
        <td><%= sigesp_solicitud.monbasinm %></td>
        <td><%= sigesp_solicitud.montotcar %></td>
        <td><%= sigesp_solicitud.tipo_destino %></td>
        <td><%= sigesp_solicitud.cod_pro %></td>
        <td><%= sigesp_solicitud.ced_bene %></td>
        <td><%= sigesp_solicitud.firnivsol %></td>
        <td><%= sigesp_solicitud.firnivadm %></td>
        <td><%= sigesp_solicitud.firnivpre %></td>
        <td><%= sigesp_solicitud.estapro %></td>
        <td><%= sigesp_solicitud.fecaprsep %></td>
        <td><%= sigesp_solicitud.codaprusu %></td>
        <td><%= sigesp_solicitud.numpolcon %></td>
        <td><%= sigesp_solicitud.fechaconta %></td>
        <td><%= sigesp_solicitud.fechaanula %></td>
        <td><%= sigesp_solicitud.monbasinmaux %></td>
        <td><%= sigesp_solicitud.montotcaraux %></td>
        <td><%= sigesp_solicitud.montoaux %></td>
        <td><%= sigesp_solicitud.undadm %></td>
        <td><%= sigesp_solicitud.destino %></td>
        <td><%= sigesp_solicitud.cod_servicio %></td>
        <td><%= sigesp_solicitud.cod_sede %></td>
        <td><%= sigesp_solicitud.cod_region %></td>
        <td><%= sigesp_solicitud.str_codregionsedeservicio %></td>
        <td><%= link_to 'Show', sigesp_solicitud %></td>
        <td><%= link_to 'Edit', edit_sigesp_solicitud_path(sigesp_solicitud) %></td>
        <td><%= link_to 'Destroy', sigesp_solicitud, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solicitud', new_sigesp_solicitud_path %>

app/views/sigesp/solicitudsalmacens/new.html.erb
<h1>New sigesp_solicitud</h1>

<%= render 'form' %>

<%= link_to 'Back', sigesp_solicituds_path %>

app/views/sigesp/solicitudsalmacens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codemp:</strong>
  <%= @sigesp_solicitud.codemp %>
</p>

<p>
  <strong>Numsol:</strong>
  <%= @sigesp_solicitud.numsol %>
</p>

<p>
  <strong>Codtipsol:</strong>
  <%= @sigesp_solicitud.codtipsol %>
</p>

<p>
  <strong>Coduniadm:</strong>
  <%= @sigesp_solicitud.coduniadm %>
</p>

<p>
  <strong>Codfuefin:</strong>
  <%= @sigesp_solicitud.codfuefin %>
</p>

<p>
  <strong>Fecregsol:</strong>
  <%= @sigesp_solicitud.fecregsol %>
</p>

<p>
  <strong>Estsol:</strong>
  <%= @sigesp_solicitud.estsol %>
</p>

<p>
  <strong>Consol:</strong>
  <%= @sigesp_solicitud.consol %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @sigesp_solicitud.monto %>
</p>

<p>
  <strong>Monbasinm:</strong>
  <%= @sigesp_solicitud.monbasinm %>
</p>

<p>
  <strong>Montotcar:</strong>
  <%= @sigesp_solicitud.montotcar %>
</p>

<p>
  <strong>Tipo destino:</strong>
  <%= @sigesp_solicitud.tipo_destino %>
</p>

<p>
  <strong>Cod pro:</strong>
  <%= @sigesp_solicitud.cod_pro %>
</p>

<p>
  <strong>Ced bene:</strong>
  <%= @sigesp_solicitud.ced_bene %>
</p>

<p>
  <strong>Firnivsol:</strong>
  <%= @sigesp_solicitud.firnivsol %>
</p>

<p>
  <strong>Firnivadm:</strong>
  <%= @sigesp_solicitud.firnivadm %>
</p>

<p>
  <strong>Firnivpre:</strong>
  <%= @sigesp_solicitud.firnivpre %>
</p>

<p>
  <strong>Estapro:</strong>
  <%= @sigesp_solicitud.estapro %>
</p>

<p>
  <strong>Fecaprsep:</strong>
  <%= @sigesp_solicitud.fecaprsep %>
</p>

<p>
  <strong>Codaprusu:</strong>
  <%= @sigesp_solicitud.codaprusu %>
</p>

<p>
  <strong>Numpolcon:</strong>
  <%= @sigesp_solicitud.numpolcon %>
</p>

<p>
  <strong>Fechaconta:</strong>
  <%= @sigesp_solicitud.fechaconta %>
</p>

<p>
  <strong>Fechaanula:</strong>
  <%= @sigesp_solicitud.fechaanula %>
</p>

<p>
  <strong>Monbasinmaux:</strong>
  <%= @sigesp_solicitud.monbasinmaux %>
</p>

<p>
  <strong>Montotcaraux:</strong>
  <%= @sigesp_solicitud.montotcaraux %>
</p>

<p>
  <strong>Montoaux:</strong>
  <%= @sigesp_solicitud.montoaux %>
</p>

<p>
  <strong>Undadm:</strong>
  <%= @sigesp_solicitud.undadm %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @sigesp_solicitud.destino %>
</p>

<p>
  <strong>Cod servicio:</strong>
  <%= @sigesp_solicitud.cod_servicio %>
</p>

<p>
  <strong>Cod sede:</strong>
  <%= @sigesp_solicitud.cod_sede %>
</p>

<p>
  <strong>Cod region:</strong>
  <%= @sigesp_solicitud.cod_region %>
</p>

<p>
  <strong>Str codregionsedeservicio:</strong>
  <%= @sigesp_solicitud.str_codregionsedeservicio %>
</p>

<%= link_to 'Edit', edit_sigesp_solicitud_path(@sigesp_solicitud) %> |
<%= link_to 'Back', sigesp_solicituds_path %>