config/routes.rb
Gorrion::Application.routes.draw do

  namespace :sigesp do
    resources :solicituds
    resources :solicitudsalmacens
  end

  devise_for :usuarios, class_name: "Administracion::Usuario"
  namespace :administracion do
    resources :usuarios do        
        get 'permisos', to: 'usuarios#permisos_usuario'
        post 'permiso/:permiso_id/add/', to: 'usuarios#add_permiso_usuario' , as: :permiso_add
        post 'permiso/:permiso_id/del/', to: 'usuarios#del_permiso_usuario', as: :permiso_del 
        get   'password' , to: 'usuarios#password_edit'
        patch 'password' , to: 'usuarios#password_save'      
      end 
  end

  namespace :sigesp do
    get 'tiposArticulos/',to: 'tipoarticulo#tiposArticulos'
    get 'articulos/', to: 'articulos#index' , as: :articulos
    get 'servicios/', to: 'sede_servicio#index', as: :servicios
    get 'unidadAdministrativas/', to: 'unidad_administrativa#index', as: :unidad_administrativas
  end

  namespace :admin do
     resources :usuarios
  end

  root 'welcome#index'

end

app/models/sigesp.rb
module Sigesp
  def self.table_name_prefix
    'sigesp_'
  end
end

app/models/sigesp/almacen.rb
class Sigesp::Almacen < ActiveRecord::Base
	self.primary_key = 'codalm'
	self.table_name = 'public.siv_almacen'

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/articulo.rb
class Sigesp::Articulo < ActiveRecord::Base
	self.primary_key = 'codart'
	self.table_name = 'public.siv_articulo'

	belongs_to :unidad, foreign_key: "codunimed", class_name: "Sigesp::Unidad"
	belongs_to :tipo_articulo, foreign_key: "codtipart", class_name: "Sigesp::TipoArticulo"

	# has_and_belongs_to_many :cargos, class_name: "Sigesp::Cargo", join_table: "public.siv_cargosarticulo", foreign_key:"codart" ,association_foreign_key: "codcar"    
    belongs_to :dt_cargo, foreign_key: "codemp", class_name: "Sigesp::DtCargo"

    has_many :cargos_articulos, class_name: "Sigesp::DtCargo", foreign_key:"codart"
	has_many :cargos, class_name: "Sigesp::Cargo", through: :cargos_articulos 


	
	self.per_page = 10 

	def cargo_activo
		if cargos.size == 0 
			return 0
		end 

		if  cargos[0].nil? 
			cargo = 0
		else
			cargo = cargos[0].porcar 
		end 
	end 

	def self.search(page = 1 , search , sort)
	    search ||= ""
   	 	sort = "codart" if sort =="codigo"
   	 	sort = "denart" if sort == "descripcion"
    
	    if search.empty? 
	      paginate(page: page).includes(:cargos).references(:cargos).order(sort) rescue paginate(page: 1).includes(:cargos).references(:cargos)
	    else
	      paginate(page: page).where("#{sort} like ?","%#{search}%").includes(:cargos).references(:cargos).order("#{sort} asc")
	    end 
	end 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/cargo.rb
class Sigesp::Cargo < ActiveRecord::Base
	self.primary_key = 'codcar'
	self.table_name = 'public.sigesp_cargos'

	belongs_to :dt_cargo, foreign_key: "codemp", class_name: "Sigesp::DtCargo"

	belongs_to :solicitud_cargo, foreign_key: "codemp", class_name: "Sigesp::SolicitudCargo"

	has_many :articulos_cargos, class_name: "Sigesp::DtCargo", foreign_key:"codcar"
	has_many :articulos, class_name: "Sigesp::Articulo", through: :articulos_cargos 


	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/ctrl_requisicion.rb
class Sigesp::CtrlRequisicion < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'sigesp_espc.sigesp_ctrl_requisicion'

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/cuenta_gasto.rb
class Sigesp::CuentaGasto < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_cuentagasto'

	belongs_to :solicitud, foreign_key: "numsol", class_name: "Sigesp::Solicitud"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/departamento.rb
class Sigesp::Departamento < ActiveRecord::Base
	self.primary_key = 'coddep'
	self.table_name = 'sigesp_espc.sno_departamento'

	belongs_to :responsable, foreign_key: "codperresponsable",class_name: "Sigesp::Persona" 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/dt_articulo.rb
class Sigesp::DtArticulo < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_dt_articulos'

	belongs_to :solicitud, foreign_key: "numsol", class_name: "Sigesp::Solicitud"
	belongs_to :articulo, foreign_key: "codart", class_name: "Sigesp::Articulo"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/dt_cargo.rb
class Sigesp::DtCargo < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_dta_cargos'

	belongs_to :cargo, class_name: "Sigesp::Cargo", foreign_key:"codcar"
    belongs_to :articulo, class_name: "Sigesp::Articulo", foreign_key:"codart"


	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/dts_cargo.rb
class Sigesp::DtsCargo < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_dts_cargos'

	belongs_to :cargo, foreign_key: "codcar", class_name: "Sigesp::Cargo"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/fuente_financiamiento.rb
class Sigesp::FuenteFinanciamiento < ActiveRecord::Base
	self.primary_key = 'codfuefin'
	self.table_name = 'public.sigesp_fuentefinanciamiento'

	 belongs_to :spg_ep3, foreign_key: "codemp", class_name: "Sigesp::SpgEp3"
	 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/marca.rb
class Sigesp::Marca < ActiveRecord::Base
	self.primary_key = 'str_idmarca'
	self.table_name = 'sigesp_espc.siv_marca'

	has_many :modelos, class_name: "Sigesp::Modelo", foreign_key:"str_idmarca"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end  
end

app/models/sigesp/modelo.rb
class Sigesp::Modelo < ActiveRecord::Base
	self.primary_key = 'id_modelo'
	self.table_name = 'sigesp_espc.siv_modelo'

	belongs_to :marca, foreign_key: "str_idmarca", class_name: "Sigesp::Marca" 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/persona.rb
class Sigesp::Persona < ActiveRecord::Base
	self.primary_key = 'codper'
	self.table_name = 'public.sno_personal'
	
	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/region.rb
class Sigesp::Region < ActiveRecord::Base
	self.primary_key = 'seq_region'
	self.table_name = 'sigesp_espc.sigesp_regiones'
	
	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/sede.rb
class Sigesp::Sede < ActiveRecord::Base
	self.primary_key = 'seq_sede'
	self.table_name = 'sigesp_espc.sigesp_sedes'

	belongs_to :region, foreign_key: "int_region",class_name: "Sigesp::Region" 
	has_and_belongs_to_many :servicios, class_name: "Sigesp::Servicio",join_table: "sigesp_espc.sigesp_serviciosedes",foreign_key:"int_sede" ,association_foreign_key: "int_servicio"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end

end

app/models/sigesp/servicio.rb
class Sigesp::Servicio < ActiveRecord::Base

	self.primary_key = 'seq_servicio'
	self.table_name = 'sigesp_espc.sigesp_servicios'

	belongs_to :tipo_servicio, foreign_key: "codtipser", class_name: "Sigesp::TipoServicio"  

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/solicitud.rb
class Sigesp::Solicitud < ActiveRecord::Base
	self.primary_key = 'numsol'
	self.table_name = 'public.sep_solicitud'

	  has_many :cuentaGastos, class_name: "Sigesp::CuentaGasto", foreign_key:"numsol"
    has_many :solicitudUsers, class_name: "Sigesp::SolicitudUser", foreign_key:"numsol"
    has_many :solicitudTipos, class_name: "Sigesp::SolicitudTipo", foreign_key:"numsol"
    has_many :dtArticulos, class_name: "Sigesp::DtArticulo", foreign_key: "numsol"
    
    belongs_to :solicitud_cargo, foreign_key: "codemp", class_name: "Sigesp::SolicitudCargo"
    belongs_to :unidadAdministrativa, foreign_key: "coduniadm", class_name: "Sigesp::UnidadAdministrativa"
    belongs_to :tipoSolicitud, foreign_key: "codtipsol", class_name: "Sigesp::TipoSolicitud"

    belongs_to :sede , foreign_key: "cod_sede", class_name: "Sigesp::Sede"
    belongs_to :servicio, foreign_key:"cod_servicio", class_name: "Sigesp::Servicio"

    belongs_to :fuenteFinanciamiento,foreign_key:"codfuefin", class_name: "Sigesp::FuenteFinanciamiento"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end


  def self.search_compra(page = 1 , search , sort)
    search ||= ""
    sort ||= "" 
    join =" INNER JOIN sigesp_espc.sep_solicitud_tipo ON sigesp_espc.sep_solicitud_tipo.numsol = public.sep_solicitud.numsol" 
    if search.empty? 
      joins(join).paginate(page: page).where("sigesp_espc.sep_solicitud_tipo.bol_compra = true ").order(sort) #rescue paginate(page: 1) 
    else
      paginate(page: page).where("#{sort} like ?","%#{search}%").order("#{sort} asc")
    end 
  end 

  def self.search_almacen(page = 1 , search , sort)
    search ||= ""
    sort ||= "" 
    join =" INNER JOIN sigesp_espc.sep_solicitud_tipo ON sigesp_espc.sep_solicitud_tipo.numsol = public.sep_solicitud.numsol" 
    if search.empty? 
      joins(join).paginate(page: page).where("sigesp_espc.sep_solicitud_tipo.bol_compra = false ").order(sort) #rescue paginate(page: 1) 
    else
      paginate(page: page).where("#{sort} like ?","%#{search}%").order("#{sort} asc")
    end 
  end 



   self.per_page = 10 

end

app/models/sigesp/solicitud_cargo.rb
class Sigesp::SolicitudCargo < ActiveRecord::Base
	self.primary_key = 'codemp'
	self.table_name = 'public.sep_solicitudcargos'

	has_many :cargos, class_name: "Sigesp::Cargo", foreign_key:"codemp"
    has_many :solicituds, class_name: "Sigesp::Solicitud", foreign_key:"codemp"

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/models/sigesp/solicitud_tipo.rb
class Sigesp::SolicitudTipo < ActiveRecord::Base
	self.primary_key = 'numsol'
	self.table_name = 'sigesp_espc.sep_solicitud_tipo'

	belongs_to :solicitud, foreign_key: "numsol", class_name: "Sigesp::Solicitud" 

	def id 
		sync_with_transaction_state
		read_attribute(self.class.primary_key)
	end
end

app/views/sigesp/solicituds/_form.html.erb
<%= form_for(@sigesp_solicitud,html: {class:'form-horizontal', role:'form'})  do |f| %>
  <% if @sigesp_solicitud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sigesp_solicitud.errors.count, "error") %> prohibited this sigesp_solicitud from being saved:</h2>
      <ul>
      <% @sigesp_solicitud.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :cod_sede, class:"col-md-2 control-label" do |n| %>
      Sede
    <% end %>
    <div class="col-md-3">
       <%= f.collection_select :cod_sede, Sigesp::Sede.all, :seq_sede, :str_descripcion, options={prompt: 'Seleccione'}, 
           html_options={class: "form-control input-sm",data: { url: sigesp_servicios_path }} %>
    </div>
    <%= f.label :cod_servicio, class:"col-md-2 control-label" do |n| %>
      Servicio
     <% end %>
    <div class="col-md-3">
       <%= f.collection_select :cod_servicio, [], :seq_servicio, :str_descripcion, options={prompt: 'Seleccione'}, html_options={class: "form-control input-sm"} %>
    </div>
  </div> <!-- end form group-->
  <div class="form-group">
    <%= f.label :codfuefin, class:"col-md-2 control-label" do |n| %>
      Fuente Financiamiento
    <% end %>
    <div class="col-md-3">
       <%= f.collection_select :codfuefin, Sigesp::FuenteFinanciamiento.all, :codfuefin, :denfuefin, options={prompt: 'Seleccione'}, html_options={class: "form-control input-sm", data: 
        { url: sigesp_unidad_administrativas_path }} %>
    </div>
    <%= f.label :unidadAdministrativa, class:"col-md-2 control-label" do |n| %>
      Unidad Ejecutora
    <% end %>
    <div class="col-md-3">
       <%= f.collection_select :unidadAdministrativa,[], :codemp, :denuniadm, options={prompt: 'Seleccione'}, html_options={class: "form-control input-sm"} %>
    </div>
  </div> 
  <div class="form-group">
    <%= f.label :consol, class:"col-md-2 control-label" do |n| %>
      Concepto Solicitud
    <% end %>
    <div class="col-md-8">
       <%= f.text_area :consol, class: "form-control input-sm", rows:"2" %>
    </div>
  </div>

  <label><strong>DETALLE DE LA REQUISICION</strong></label>

  <div class="form-group">
    <div class="col-md-10">
      <div align="right"> 
        <button type="button" class="btn btn-primary" id="prueba" data-url="<%= sigesp_tiposArticulos_path %>"data-url-articulo="<%= sigesp_articulos_path %>">
        <span class="glyphicon glyphicon-plus " aria-hidden="true"></span>
        </button>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th> Código </th>
            <th> Item </th> 
            <th> Cantidad </th>
            <th> Precio </th>
            <th> Unidad </th>
            <th> SubTotal </th>
            <th></th>
          </tr>
        </thead> 
        <tbody class="detallesolictud">
        </tbody>
      </table>
      <div  align="right">
        <label class="total"> Total :</label>
      </div>
    </div>
  </div>



  <div class=" form-group">
    <div class="col-md-7">
    </div>
    <div class="col-md-1">
      <%= f.submit "Guardar" , id: "pp", class: "btn btn-default "  %>
    </div>
    <div class="col-md-1">
      <%= f.submit "Cancelar" , id: "pp", class: "btn btn-default "  %>
    </div>
  </div> 

<% end %>

app/views/sigesp/solicituds/index.html.erb
<h1 class="page-header"> Solicitudes Compra </h1>
<div  class="botonera">
      <%= link_to new_sigesp_solicitud_path,  class: " btn btn-default " do %>
        agregar
      <% end %>
</div>

<div class="table-responsive">

<div class="row buscar" >
    <div class="col-md-6"></div>
    <div class="col-md-6" align="rigth">
    <div class="col-md-6">  
       <%= text_field_tag :search,params[:search],class: "form-control" %>  
    </div>
    <div class="col-md-3">
       <%= select_tag :sort,options_for_select(["numero solicitud","descripcion","concepto","tipo","fecha","estado"]), class: "form-control",selected:params[:sort]%>
    </div>
    <div class="col-md-3">
       <%= content_tag :button,'Buscar',class: "btn btn-default buscararticulo" %>
      </div>
    </div> 
  </div>

  <table class="table">
  <thead>
    <tr>
      <th>Nro</th>
      <th>Unidad Ejecutora</th> 
      <th>Concepto</th> 
      <th>Tipo</th>
      <th>Fecha</th>
      <th>Estado</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
 
  <tbody>
    <% @sigesp_solicituds.each do |sigesp_solicitud| %>
      <tr>
         <td><%= sigesp_solicitud.numsol %></td>
         <td><%= sigesp_solicitud.unidadAdministrativa.denuniadm  %></td>
         <td><%= truncate(sigesp_solicitud.consol,length: 75) %></td>
         <td><%= tipoSolicitud(sigesp_solicitud.tipoSolicitud.dentipsol) %></td>
         <td><%= sigesp_solicitud.fecregsol %></td>
         <td><%= estadoSolicitud(sigesp_solicitud.estsol) %></td>
         <td><%= link_to sigesp_solicitud do |link| %>
            <span data-toggle="tooltip" data-placement="left" title="" class="glyphicon glyphicon-zoom-in" title="Mostrar"></span>
        <% end %>
        </td>
         <td><%= link_to sigesp_solicitud, method: :delete, data: { confirm: 'Quieres Anular Esta Solicitud  ?' } do |link| %>
            <span data-toggle="tooltip" data-placement="left" title="Eliminar" class="glyphicon glyphicon-remove"></span>
          <% end %>
         </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="row">
  <div class="col-md-4">
    <label><%= page_entries_info @sigesp_solicituds %></label>
  </div>
  <div class="col-md-8" align="right">
    <%= will_paginate @sigesp_solicituds, renderer: BootstrapPagination::Rails %> 
  </div>
</div>

app/views/sigesp/solicituds/new.html.erb
<div class="row page-header">
	<div class="col-md-8">
		<h4>DATOS DE LA REQUISICION</h4>
	</div>
	<div class="col-md-4" align="right" >
		<%= link_to 'Regresar', sigesp_solicituds_path,class:"btn btn-default" %>				
	</div>
</div>
<div class="row formulario_solcitud" url="<%= sigesp_solicituds_path %>" > 
	<%= render 'form' %>
</div>

app/views/sigesp/solicituds/show.html.erb
<div class="row page-header">
  <div class="col-md-8">
    <h2> Solicitud de Compras :  <%= @sigesp_solicitud.numsol  %> -- 
 </h2>
  </div>
  <div class="col-md-4" align="right" >
      <%= link_to 'Regresar', sigesp_solicituds_path ,class:"btn btn-default" %>
  </div>
</div>

<% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>


<div class="row">
  <div class="col-md-2">
    <strong>Codigo</strong>
  </div>
  <div class="col-md-2">  
    <%= @sigesp_solicitud.numsol  %>
  </div>
  <div class="col-md-1">
    <strong>Tipo :</strong>
  </div>
  <div class="col-md-2">
    <%= tipoSolicitud(@sigesp_solicitud.tipoSolicitud.dentipsol)  %>
  </div>
  <div class="col-md-1">
    <strong> Fecha :</strong>
  </div>
  <div class="col-md-2">
    <%= @sigesp_solicitud.fecregsol %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-2">
    <strong> Sede :</strong>
  </div>
  <div class="col-md-2">
    <%= @sigesp_solicitud.sede.str_descripcion %>
  </div>
  <div class="col-md-2">
  <strong> Servicio :</strong>
  </div>
  <div class="col-md-2">
  <%= @sigesp_solicitud.servicio.str_descripcion %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-2">
    <strong>Fuente de Financiamiento:</strong>
  </div>
  <div class="col-md-4">
    <%= @sigesp_solicitud.fuenteFinanciamiento.denfuefin  %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-2">
    <strong>Unidad Ejecutora:</strong>
  </div>
  <div class="col-md-6">
      <%= @sigesp_solicitud.unidadAdministrativa.denuniadm %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-2">
    <strong>Concepto Solicitud </strong>
  </div>
  <div class="col-md-6">
     <%= @sigesp_solicitud.consol %>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-2">
    <strong>Estado</strong>
  </div>
  <div class="col-md-4">
     <%= estadoSolicitud(@sigesp_solicitud.estsol) %>
  </div>
</div>
<br/>
<label><strong>DETALLE DE LA REQUISICION</strong></label>
<br/>
<div class="row">
  <div class="col-md-10">
    <table class="table table-hover">
     <thead>
     <tr>
       <th> Código </th>
       <th> Item </th> 
       <th> Cantidad </th>
       <th> Precio </th>
       <th> Unidad </th>
       <th> SubTotal </th>
     </tr>
     </thead> 
     <tbody>
      <%  @sigesp_solicitud.dtArticulos.each do |articulo|  %>
      <tr>
        <td><%= articulo.codart %></td>
        <td><%= articulo.articulo.denart %></td>
        <td><%= articulo.canart %> </td>
        <td><%= articulo.monart %></td>
        <td><%= articulo.unidad %></td>
        <td><%= articulo.canart * articulo.monart  %></td>
      </tr>
      <% end %>
     </tbody>
    </table> 
  </div>
</div>
<br/>

<div class="row">
  <div class="col-md-10">
    <div class="page-header" align="right">
       <p class="bg-primary" style="padding-top:10px;padding-bottom:10px;padding-right:25px;"><strong> Total :</strong> <%= @sigesp_solicitud.dtArticulos.sum("monart") * @sigesp_solicitud.dtArticulos.sum("canart") %></p> 
    </div>
  </div>
</div>