config/routes.rb
Gorrion::Application.routes.draw do

  namespace :sigesp do
    resources :solicituds
    resources :solicitudsalmacens
  end

  devise_for :usuarios, class_name: "Administracion::Usuario"
  namespace :administracion do
    resources :usuarios do        
        get 'permisos', to: 'usuarios#permisos_usuario'
        post 'permiso/:permiso_id/add/', to: 'usuarios#add_permiso_usuario' , as: :permiso_add
        post 'permiso/:permiso_id/del/', to: 'usuarios#del_permiso_usuario', as: :permiso_del 
        get   'password' , to: 'usuarios#password_edit'
        patch 'password' , to: 'usuarios#password_save'      
      end 
  end

  namespace :sigesp do
    get 'tiposArticulos/',to: 'tipoarticulo#tiposArticulos'
    get 'articulos/', to: 'articulos#index' , as: :articulos
    get 'servicios/', to: 'sede_servicio#index', as: :servicios
    get 'unidadAdministrativas/', to: 'unidad_administrativa#index', as: :unidad_administrativas
  end

  namespace :admin do
     resources :usuarios
  end

  root 'welcome#index'

end

app/models/administracion.rb
module Administracion
  def self.table_name_prefix
    'administracion_'
  end
end

app/models/administracion/controlador.rb
class Administracion::Controlador < ActiveRecord::Base

   has_many  :permisos , class_name: "Administracion::Permiso"

end

app/models/administracion/permiso.rb
class Administracion::Permiso < ActiveRecord::Base
	belongs_to :controlador, class_name: "Administracion::Controlador"

	self.per_page = 10 

	def self.search(page = 1 , search , sort)
	    search ||= ""
   	 	sort ||= "" 
	    if search.empty? 
	      paginate(page: page).order(sort) rescue paginate(page: 1) 
	    else
	      paginate(page: page).where("#{sort} like ?","%#{search}%").order("#{sort} asc")
	    end 
	end 
	
end

app/models/administracion/permiso_usuario.rb
class Administracion::PermisoUsuario < ActiveRecord::Base

	belongs_to :usuario, class_name: "Administracion::Usuario"
	belongs_to :permiso, class_name: "Administracion::Permiso"

	self.per_page = 10 

	def self.search(page = 1 , search , sort)
	    search ||= ""
   	 	sort ||= "" 
	    if search.empty? 
	      paginate(page: page).order(sort) rescue paginate(page: 1) 
	    else
	      paginate(page: page).where("#{sort} like ?","%#{search}%").order("#{sort} asc")
	    end 
	end 
end

app/models/administracion/usuario.rb
class Administracion::Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end


  def self.search(page = 1 , search , sort)
    search ||= ""
    sort ||= "" 

    if search.empty? 
      paginate(page: page).order(sort) rescue paginate(page: 1) 
    else
      paginate(page: page).where("#{sort} like ?","%#{search}%").order("#{sort} asc")
    end 
  end 


  ######################### Validacion ##############################################


  validates :username , 
      presence: {message: ' Ingrese un username '},
      uniqueness: {message: 'ya Registrado', on: :create },
      length: {maximum: 15 , too_long:"%{count} caracteres es el maximo  "}

  validates :email, 
         presence: {message: 'Ingrese su Email '},
         format:{ with:/.+@+[a-z]+./ , message: "Formato Invalido"}

  validates :cedula, 
      presence: {message: 'Ingrese su Cedula '},
      uniqueness: {message: 'Cedula Registrada', on: :create },
      length: {maximum: 15 , too_long:"%{count} caracteres es el maximo  "},
      format: { with: /V-\d/, message: "Formato Invalido"}

  validates :nombres,
      presence: {message: 'Ingrese Su Nombre '},
      length: {maximum: 40, too_long:"%{count} caracteres es el maximo  "}

  validates :apellidos,
      presence: {message: 'Ingrese Su apellido '},
      length: {maximum: 40, too_long:"%{count} caracteres es el maximo  "}

  validates :celular,
      length: {maximum: 15, too_long:"%{count} caracteres es el maximo  "}

  validates :telefono,
      length: {maximum: 15, too_long:"%{count} caracteres es el maximo  "}

  validates :direccion,
      length: {maximum: 250, too_long:"%{count} caracteres es el maximo  "}


   has_many  :permiso_usuarios , class_name: "Administracion::PermisoUsuario"
   has_many  :permisos, through: :permiso_usuarios , class_name: "Administracion::Permiso"

  self.per_page = 10 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/administracion/usuarios_controller.rb
class Administracion::UsuariosController < ApplicationController
  
  #load_and_authorize_resource

  before_action :set_administracion_usuario, only: [:show, :edit, :update,:destroy,
                :permisos_usuario,:add_permiso_usuario, :del_permiso_usuario,
                :permisos_usuario_edit,:password_edit, :password_save]


  #before_action :authenticate_usuario!

  # GET /administracion/usuarios
  # GET /administracion/usuarios.json
  def index
    @usuarios = Administracion::Usuario.search params[:page], params[:search], params[:sort]
  end
 
  # GET /administracion/usuarios/1
  # GET /administracion/usuarios/1.json
  def show

  end

  # GET /administracion/usuarios/new
  def new
    @administracion_usuario = Administracion::Usuario.new
  end

  # GET /administracion/usuarios/1/edit
  def edit
    @administracion_usuario.password_confirmation = @administracion_usuario.password
  end

  def password_edit

  end 

  def password_save
      respond_to do |format|
      if @administracion_usuario.update(usuario_params_change_password)
        flash[:notice] = "Usuario Contraseña Actualizada  ."
        format.html { redirect_to @administracion_usuario, notice: 'Usuario Contraseña Actualizada  .' }
        format.json { render action: 'show', status: :created, location: @administracion_usuario}
      else
        format.html { render action: 'password_edit' }
        format.json { render json: @administracion_usuario.errors, status: :unprocessable_entity }
      end
    end

  end 


  # POST /administracion/usuarios
  # POST /administracion/usuarios.json
  def create
    @administracion_usuario = Administracion::Usuario.new(usuario_params)
    @administracion_usuario.password = '12345678'
    @administracion_usuario.password_confirmation= '12345678'
    @administracion_usuario.username = @administracion_usuario.username.upcase 
    respond_to do |format|
      if @administracion_usuario.save
        flash[:notice] = "Usuario Almacenado Correctamente "
        format.html { redirect_to @administracion_usuario }
        format.json { render action: 'show', status: :created, location: @administracion_usuario}
      else
        format.html { render action: 'new' }
        format.json { render json: @administracion_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administracion/usuarios/1
  # PATCH/PUT /administracion/usuarios/1.json
  def update
    respond_to do |format|
      if @administracion_usuario.update(usuario_params_update )
        flash[:notice] = "Usuario fue correctamente actualizado."
        format.html { redirect_to @administracion_usuario}
        format.json { render action: 'show', status: :created, location: @administracion_usuario}
      else
        format.html { render action: 'edit' }
        format.json { render json: @administracion_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administracion/usuarios/1
  # DELETE /administracion/usuarios/1.json
  def destroy
    @administracion_usuario.destroy
    respond_to do |format|
      format.html { redirect_to administracion_usuarios_url }
      format.json { head :no_content }
    end
  end

  #Mostrar todo los permisos del usuario 
  def permisos_usuario
    @controladores = Administracion::Controlador.all
  end 
 
  #Mostrar todo los permisos del usuario 
  def permisos_usuario_edit

  end 

  def add_permiso_usuario
    @permiso = Administracion::Permiso.find(params[:permiso_id])
    @administracion_usuario.permisos 
    unless @administracion_usuario.permisos.find { |permiso| permiso == @permiso } 
      @permiso_usuario = Administracion::PermisoUsuario.new
      @permiso_usuario.usuario = @administracion_usuario
      @permiso_usuario.permiso = @permiso
      @permiso_usuario.save 
      flash[:notice] = "Permiso Activado "+@permiso.descripcion
    else
      flash[:notice] = "Este Permiso se Encuentra Asigando "+@permiso.descripcion
    end 
    respond_to do |format|
      format.html { redirect_to administracion_usuario_permisos_path(@administracion_usuario)}
      format.json { head :no_content }
    end
  end


  def del_permiso_usuario
    @permiso = Administracion::Permiso.find(params[:permiso_id])
    @permiso_usuario = @administracion_usuario.permiso_usuarios.find {
      |permiso| permiso.permiso == @permiso } 

    unless @permiso_usuario.nil?
      @permiso_usuario.destroy
      flash[:notice] = "Permiso Inactivo"+@permiso.descripcion
    else
      flash[:notice] = "Este Permiso No se Encuentra Asigando"+@permiso.descripcion
    end 

    respond_to do |format|
      format.html { redirect_to administracion_usuario_permisos_path(@administracion_usuario)}
      format.json { head :no_content }
    end

  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administracion_usuario
      if params[:id].nil?
        @administracion_usuario = Administracion::Usuario.find(params[:usuario_id])
      else
        @administracion_usuario = Administracion::Usuario.find(params[:id])
      end
    end

    def usuario_params
      params.require(:administracion_usuario).permit(:cedula, :nombres, :apellidos,:email, :direccion, :telefono, :celular ,:username)
    end

    def usuario_params_update
      params.require(:administracion_usuario).permit(:nombres, :apellidos,:email, :direccion, :telefono, :celular)
    end
 
    def usuario_params_change_password
      params.require(:administracion_usuario).permit(:password,:password_confirmation)
    end

    def permiso_edit
      params.require(:permiso).permit(:permis_id)
    end

end

app/helpers/administracion/usuarios_helper.rb
module Administracion::UsuariosHelper
  def permisos_activos(permisos,usuario)
		contenedor = []
		permisos.each do |permiso|
			if usuario.permisos.find{|p| p.id == permiso.id }.nil?
				a = content_tag :a,class: "list-group-item" do |a|
					row = content_tag :div, class: "row" do |row|
						[ 
							content_tag(:div,content_tag(:span,"\t"+permiso.descripcion,class: "glyphicon glyphicon-remove",title:"PERMISO INACTIVO"),class: "col-md-6"),
							content_tag(:div,button_to("AGREGAR",administracion_usuario_permiso_add_path(usuario,permiso), class: "btn btn-default", method: "post",  data: { confirm: 'Quieres Activar este Permiso ?' } ),class: "col-md-6"),						  
						].join.html_safe
					end 
				end 
				contenedor.append a
			else
				a = content_tag :a,class: "list-group-item" do |a|
					row = content_tag :div, class: "row" do |row|
						[ 
							content_tag(:div,content_tag(:span,"\t"+permiso.descripcion,class: "glyphicon glyphicon-ok",title:"PERMISO ACTIVO"),class: "col-md-6"),
							content_tag(:div,button_to("QUITAR",administracion_usuario_permiso_del_path(usuario,permiso), class: "btn btn-default", method: "post", data: { confirm: 'Quieres Inactivar este Permiso ?' } ),class: "col-md-6"),						  
						].join.html_safe
					end 
				end 
				contenedor.append a
			end 
		end
		div = content_tag :div , class:"list group permisos_usuario" do |div|
			contenedor.join.html_safe
		end  
	end 
end 

app/views/administracion/usuarios/_form.html.erb
<%= form_for(@administracion_usuario,html: {class:'form-horizontal', role:'form'})  do |f| %>

  <div class="form-group">
    <%= f.label :cedula , class: "col-sm-2 control-label" %>
    <div class="col-sm-4" >
      <% if controller.action_name == "new" %>
        <%= f.text_field :cedula ,class: "form-control",placeholder: "V-000000", maxlength:10 %>
      <% else %>
        <%= f.text_field :cedula ,class: "form-control",placeholder: "V-000000", maxlength:10, disabled:"true" %>
      <% end %>
    </div>
    <%= f.label :email , class:"col-sm-1 control-label" %>
    <div class="col-sm-4" >
      <%= f.text_field :email, class:"form-control input-sm ", maxlength:40 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :nombres , class:"col-sm-2 control-label" %>
    <div class="col-sm-9" >
      <%= f.text_field :nombres, class:"form-control input-sm ", maxlength:40 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :apellidos , class:"col-sm-2 control-label" %>
    <div class="col-sm-9" >
      <%= f.text_field :apellidos, class:"form-control input-sm ", maxlength:40 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :telefono , class:"col-sm-2 control-label" %>
    <div class="col-sm-4" >
      <%= f.text_field :telefono, class:"form-control input-sm ", maxlength:15 %>
    </div>

    <%= f.label :celular , class:"col-sm-1 control-label" %>
    <div class="col-sm-4" >
      <%= f.text_field :celular, class:"form-control input-sm ", maxlength:15 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :direccion , class:"col-sm-2 control-label" %>
    <div class="col-sm-9" >
      <%= f.text_area :direccion, class:"form-control input-sm ", maxlength:250 %>
    </div>
  </div>
  <h3 class="page-header"> Datos de Acceso </h3>
  <div class="form-group" >
    <%= f.label :username , class:"col-sm-2 control-label" %>
    <div class="col-sm-4" >
      <% if controller.action_name == "new" %>
        <%= f.text_field :username,class:"form-control input-sm ", maxlength:15 %>
      <% else %>
        <%= f.text_field :username,class:"form-control input-sm ", maxlength:15,disabled:"true" %>
      <% end %>
    </div>
  </div>
  <div class=" form-group">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-9">
      <%= f.submit "Guardar" , id: "pp", class: "btn btn-default "  %>
    </div>
  </div> 
<% end %>

app/views/administracion/usuarios/_usuario.html.erb
<tr>
    <td><%= usuario.username %></td>
	<td><%= usuario.cedula %></td>
	<td><%= usuario.nombres %></td>
	<td><%= usuario.apellidos  %></td>
	<td><%= usuario.email  %></td>
	<td><%= usuario.celular  %></td>
    <% if controller.action_name == 'index' %>
		<td>
    		<%= link_to  usuario do |link| %>
    			<span data-toggle="tooltip" data-placement="left" title="" class="glyphicon glyphicon-zoom-in" title="Mostrar"></span>
    		<% end %>	
	    </td>
    	<td>
	    	<%= link_to  edit_administracion_usuario_path(usuario) do |link| %>
    		<span data-toggle="tooltip" data-placement="left" class="glyphicon glyphicon-edit" title="Editar"></span>
	    	<% end %>
    	</td>
    	<td>
	    	<%= link_to  administracion_usuario_permisos_path (usuario) do |link| %>
    		<span data-toggle="tooltip" data-placement="left" class="glyphicon glyphicon-th-large" title="Permisos"></span>
	    	<% end %>
    	</td>

    	<td>
	    	<%= link_to  administracion_usuario_password_path (usuario) do |link| %>
    		<span data-toggle="tooltip" data-placement="left" class="glyphicon glyphicon-lock" title="Cambiar Contraseña "></span>
	    	<% end %>
    	</td>

   		<td>
   			<%= link_to usuario, method: :delete, data: { confirm: 'Quieres Eliminar este Usuario ?' } do |link| %>
    		<span data-toggle="tooltip" data-placement="left" title="Eliminar" class="glyphicon glyphicon-remove"></span>
    	<% end %>
   	</td>
	<% end %>
</tr> 
 

app/views/administracion/usuarios/edit.html.erb
<div class="row page-header">
	<div class="col-md-2">
		<h3> Editar Usuario </h3>
	</div>
	<div class="col-md-10" align="right" >
			<%= link_to 'Usuario', @administracion_usuario , class:"btn btn-default" %>  
			<%= link_to 'Regresar',  administracion_usuarios_path ,class:"btn btn-default" %>			
	</div>
</div>
<div class="row formulariousuario_nuevo" url="<%= administracion_usuarios_path %>" > 
	<%= render 'form' %>
</div>

app/views/administracion/usuarios/index.html.erb
<h1 class="page-header"> Usuarios </h1>
<div  class="botonera">
      <%= link_to new_administracion_usuario_path,  class: " btn btn-default " do %>
        agregar
      <% end %>
</div>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>UserName</th>
        <th>Cedula</th>
        <th>Nombres</th>
        <th>Apellidos</th>
        <th>Email</th>
        <th>Celular</th>
      </tr>
    </thead>
   <tbody>
      <%= render  @usuarios %>
   </tbody>
  </table>
</div>
  
<div class="row">
  <div class="col-md-4">
    <label><%= page_entries_info @usuarios %></label>
  </div>
  <div class="col-md-8" align="right">
    <%= will_paginate @usuarios, renderer: BootstrapPagination::Rails %> 
  </div>
</div>

app/views/administracion/usuarios/new.html.erb
<div class="row page-header">
	<div class="col-md-2">
		<h3> Editar Usuario </h3>
	</div>
	<div class="col-md-10" align="right" >
		<%= link_to 'Regresar', administracion_usuarios_path,class:"btn btn-default" %>				
	</div>
</div>
<div class="row formulariousuario_nuevo" url="<%= administracion_usuarios_path %>" > 
	<%= render 'form' %>
</div>

app/views/administracion/usuarios/password_edit.html.erb
<div class="row page-header">
  <div class="col-md-2">
    <h2> Usuario </h2>
  </div>
  <div class="col-md-10" align="right" >
      <%= link_to 'Regresar',  administracion_usuarios_path ,class:"btn btn-default" %>     
  </div>
</div>
<div class="formulariousuario_contrasena" url="<%= administracion_usuarios_path %>" >
<%= form_for(@administracion_usuario,url:administracion_usuario_password_path(@administracion_usuario) ,html: {class:'form-horizontal',role:'form'}) do |f| %>
  <h3 class="page-header"> Datos de Acceso </h3>
  <div class="form-group" >
    <%= f.label :username , class:"col-sm-2 control-label" %>
    <div class="col-sm-4" >
      <%= f.text_field :username,class:"form-control input-sm ", maxlength:15, disabled: "true" %>
    </div>
  </div>
  <div class="form-group" >
    <%= f.label :password , class:"col-sm-2 control-label" %>
    <div class="col-sm-4" >
      <%= f.password_field :password, class:"form-control input-sm ", maxlength:20 %>
    </div>
    <div class="col-sm-3">
      <% if @administracion_usuario.errors[:password].size != 0 %>
        <label class="label label-danger" ><%= @administracion_usuario.errors[:password].join(" ") %> </label>
      <% else %>
        <label> Ingrese como Minimo 8 characteres</label>
      <% end %>
    </div>
  </div>

  <div class="form-group" >
    <%= f.label :password_confirmation , class:"col-sm-2 control-label" %>
    <div class="col-sm-4" >
        <%= f.password_field :password_confirmation, class:"form-control input-sm ", maxlength:20 %>
    </div>
    <div class="col-sm-3">
      <% if @administracion_usuario.errors[:password_confirmation].size != 0 %>
        <label class="label label-danger" ><%= @administracion_usuario.errors[:password_confirmation].join(" ") %> </label>
     <% end %>
    </div>
  </div>
  <div class=" form-group">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-9">
      <%= f.submit "Guardar" , class: "btn btn-default " %>
    </div>
  </div> 
<% end %>
</div>

app/views/administracion/usuarios/permisos_usuario.html.erb
<div class="row page-header">
  <div class="col-md-2">
    <h2> Usuario </h2>
  </div>
  <div class="col-md-10" align="right" >
    <%= link_to 'Editar', edit_administracion_usuario_path(@administracion_usuario), class:"btn btn-default" %> 
      <%= link_to 'Regresar',  administracion_usuarios_path ,class:"btn btn-default" %>
  </div>
</div>
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row" style="">
		  <div class="col-md-4">
		    <label class="list-group-item-heading"
		    	 style="font-weight: bold;">UserName 
			    <%= @administracion_usuario.username  %>
		    </label>
		  </div>
		  <div class="col-md-4">
		    <label class="list-group-item-heading"
		    	 style="font-weight: bold;">Cedula 
			    <%= @administracion_usuario.cedula  %>
		    </label>
		  </div>
		  <div class="col-md-4">
		    <label class="list-group-item-heading"
		    	 style="font-weight: bold;">Nombres 
			    <%= @administracion_usuario.nombres  %>
		    </label>
		  </div>

		</div>
	</div>
</div>

<% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= notice %>
    	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
 			 <span aria-hidden="true">&times;</span>
		</button>
	</div>
<% end %>

<h3 class="page-header"> Permisos </h3>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @controladores.each do |controlador|   %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="<%= controlador.id%>">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#<%= controlador.id %>c" aria-controls="<%= controlador.id %>c">
          <%= controlador.descripcion %>
        </a>
      </h4>
    </div>
    <div id="<%= controlador.id %>c" class="panel-collapse collapse " role="tabpanel" aria-labelledby="<%= controlador.id%>">
      <div class="panel-body">
      	<%=  permisos_activos(controlador.permisos,@administracion_usuario)   %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/administracion/usuarios/show.html.erb
<div class="row page-header">
  <div class="col-md-2">
    <h2> Usuario </h2>
  </div>
  <div class="col-md-10" align="right" >
    <%= link_to 'Editar', edit_administracion_usuario_path(@administracion_usuario), class:"btn btn-default" %> 
      <%= link_to 'Regresar',  administracion_usuarios_path ,class:"btn btn-default" %>     
  </div>
</div>

<% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>


<div class="panel panel-default">
<div class="panel-body">
<div class="row" style="margin: 10px 0px 10px 0px;">
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">UserName</h4>
  </div>
  <div class="col-md-4">
    <p  class="list-group-item-text"><%= @administracion_usuario.username  %></p>
  </div>
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">Cedula</h4>
  </div>
  <div class="col-md-4">
    <p  class="list-group-item-text"><%= @administracion_usuario.cedula  %></p>
  </div>
</div>

<div class="row" style="margin: 0px 0px 10px 0px;">
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">Nombres</h4>
  </div>
  <div class="col-md-4">
    <p  class="list-group-item-text"><%= @administracion_usuario.nombres  %></p>
  </div>
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">Apellidos</h4>
  </div>
  <div class="col-md-4">
    <p  class="list-group-item-text"><%= @administracion_usuario.apellidos  %></p>
  </div>
</div>

<div class="row" style="margin: 0px 0px 10px 0px;">
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">Email</h4>
  </div>
  <div class="col-md-4">
    <p  class="list-group-item-text"><%= @administracion_usuario.email  %></p>
  </div>
</div>

<div class="row" style="margin: 0px 0px 10px 0px;">
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">Telefono</h4>
  </div>
  <div class="col-md-4">
    <p  class="list-group-item-text"><%= @administracion_usuario.telefono  %></p>
  </div>
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">Celular</h4>
  </div>
  <div class="col-md-4">
    <p  class="list-group-item-text"><%= @administracion_usuario.celular  %></p>
  </div>
</div>


<div class="row" style="margin: 0px 0px 10px 0px;">
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">Direccion</h4>
  </div>
  <div class="col-md-4">
    <p  class="list-group-item-text"><%= @administracion_usuario.direccion  %></p>
  </div>
</div>


<div class="row" style="margin: 0px 0px 10px 0px;">
  <div class="col-md-2">
    <h4 class="list-group-item-heading" style="font-weight: bold;">Estado</h4>
  </div>
  <div class="col-md-4">
    <p class="list-group-item-text"><%=if @administracion_usuario.estado then "Activo" else "Inactivo " end  %></p>
  </div>
</div>
  </div>

</div>