config/routes.rb
Gorrion::Application.routes.draw do

  namespace :sigesp do
    resources :solicituds
    resources :solicitudsalmacens
  end

  devise_for :usuarios, class_name: "Administracion::Usuario"
  namespace :administracion do
    resources :usuarios do        
        get 'permisos', to: 'usuarios#permisos_usuario'
        post 'permiso/:permiso_id/add/', to: 'usuarios#add_permiso_usuario' , as: :permiso_add
        post 'permiso/:permiso_id/del/', to: 'usuarios#del_permiso_usuario', as: :permiso_del 
        get   'password' , to: 'usuarios#password_edit'
        patch 'password' , to: 'usuarios#password_save'      
      end 
  end

  namespace :sigesp do
    get 'tiposArticulos/',to: 'tipoarticulo#tiposArticulos'
    get 'articulos/', to: 'articulos#index' , as: :articulos
    get 'servicios/', to: 'sede_servicio#index', as: :servicios
    get 'unidadAdministrativas/', to: 'unidad_administrativa#index', as: :unidad_administrativas
  end

  namespace :admin do
     resources :usuarios
  end

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GORRION</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <span class="sr-only">Toggle navigation</span>
        </button>
        <a href="/" class="navbar-brand">Gorrion </a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
          <ul class="nav navbar-nav navbar-right">
            <% if controller.controller_name != 'sessions' and controller.action_name != 'new' %>
              <%  if usuario_signed_in? %>
                <li><a href="#">Mi cuenta </a></li>
              <% else %>
                <li><%= link_to  new_usuario_session_path do  %>
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Iniciar Session
                  <% end %>
                </li>
              <% end %>
            <%end%>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="#" style="text-align: center; font-weight: bold;" > Menu </a></li>
            <li>
              <%= link_to "Usuario",administracion_usuarios_path , style: "text-align: center; font-weight: bold;" %>
            </li>
          </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <%= yield %>       
        </div>
      </div>
    </div>
</body>
</html>